version: "3"

services:
    app:
        image: golang
        container_name: app
        volumes:
            - .:/go
        ports:
            - "6379:6379"
        command: bash -c "unset GOPATH && go build && ./kumidb"